# Generated by Django 6.0.4 on 2026-05-24 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaseCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate_id", models.CharField(max_length=64, unique=True)),
                ("token_id", models.CharField(max_length=128)),
                ("chain", models.CharField(default="Polygon", max_length=64)),
                (
                    "transaction_hash",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("metadata_uri", models.URLField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("MINTED", "Minted"),
                            ("VERIFIED", "Verified"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="MINTED",
                        max_length=15,
                    ),
                ),
                ("minted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="customer.booking",
                    ),
                ),
            ],
        ),
    ]
